### ISSUE TITLE
Examples: Parallel Training -- Shouldn't use if/else when reassinging labels

### ISSUE THREAD

**Issue by mlnichols** [civisanalytics/civis-python#100]
In the parallel training example, the labels from the Wisconsin breast cancer data set are transformed from 4,2 to 1,0.

Although this doesn't impact the result in this instance due to the data set, it is bad practice to use a single if/else loop and in an example which people for better or worse learn off, should probably be changed to something like:

df['is_cancer'] = [1 if val == 4 else (0 if val == 2 else '?') for val in df['is_cancer'] ]

This would prevent a null value in the dependent variable from being mapped to 0 which could impact the results and further illustrate that null values should be passed through to any algorithm that accepts them due to possible underlying issues with data collection.

**Comment by keithing** [comment]
That seems safer to me!  We're happy to accept pull requests [(link to contributing)](https://github.com/civisanalytics/civis-python/blob/master/CONTRIBUTING.md). Otherwise I'm sure @peterskipper would be happy to make that change.

**Comment by mlnichols** [comment]
Put in pull request for the changes. Should be np.nan instead of ?

**Comment by stephen-hoover** [comment]
Closed by PR #101 .
