### ISSUE TITLE
Model polling fails intermittently

### ISSUE THREAD

**Issue by DerrickHiggins** [civisanalytics/civis-python#149]
For some reason, when one of the models submitted for parallel training using the `civis.futures` module has `cross_validation_parameters` specified, polling with `futures.wait` does not work.

I get the following error message:
```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/Users/dch024/virtualenvs/scipy3/lib/python3.5/site-packages/civis/polling.py", line 41, in run
    if self.poller(*self.poller_args).state in DONE:
AttributeError: 'NoneType' object has no attribute 'state'
```

Can be replicated by running the [parallel training example](https://github.com/civisanalytics/civis-python/blob/master/examples/CivisML_parallel_training.ipynb)

**Comment by stephen-hoover** [comment]
Thank you for the bug report, @DerrickHiggins ! I see you're using Python v3.5.2. What version of `civis` are you using?

When you say that you get this failure in the parallel training example, do you mean cell 8,
```python
%%time 
future_jobs = [model.train(df=df) for model in models]
futures.wait(future_jobs)
```
?

Do you reliably get this error with every call? I've been unable to reproduce in either Python v3.5.2 or v3.6.2, using various versions of `civis`.

**Comment by DerrickHiggins** [comment]
Hey, @stephen-hoover -- turns out the issue is intermittent, and not related to the presence of the `cross_validation_parameters` parameter to `ModelPipeline`. (I thought it was, as it only happened with that parameter set in my limited testing.)

[Here](https://gist.github.com/DerrickHiggins/dd666e5c0c79b91415b6696a3e12c774) is a script to replicate the error.  When I run it, I get the following output:

```
3 / 30 jobs threw exceptions
27 / 30 jobs succeeded
```

This is under python 3.5.2, and with `civis-python` @ 09a92f0fea0893dfdc221f3dac2cd022c97484b6

**Comment by stephen-hoover** [comment]
@DerrickHiggins , an update on my debugging (lack of) progress -- I'm still unable to replicate. I ran the script you provided 11 times using a Python 3.5.2 conda environment and civis-python 09a92f0 , with no exceptions (OS X 10.11.6). If I get a chance this weekend, I'll try from my home network, in case a poorer network connection makes any difference.

**Comment by DerrickHiggins** [comment]
I've replicated under python 3.5.2 and 3.6.2 on my mac (OS X 10.12.6), but can't replicate on an AWS ubuntu server with any version of python.  So maybe networking or OS-related?

**Comment by mheilman** [comment]
fwiw, I'm on macOS 10.12.6 also with 3.6.2 but wasn't able to replicate the issue with your gist.

```
0 / 30 jobs threw exceptions
30 / 30 jobs succeeded
```

**Comment by DerrickHiggins** [comment]
Dunno; if no one can replicate, I'll close it.

**Comment by stephen-hoover** [comment]
I tried a couple more times this morning, and still haven't been able to replicate. Are you still seeing these errors?
