### ISSUE TITLE
BUG make sure to catch OSError when reading the cached API spec for python 2.7

### ISSUE THREAD

**Issue by beckermr** [civisanalytics/civis-python#179]
It looks like the CLI for python 2.7 is choking when trying to get a cached API spec. In python 2.7, the file not existing raises an `OSError` which is not caught in the right spot:

https://github.com/civisanalytics/civis-python/blob/master/civis/cli/__main__.py#L204

**Comment by stephen-hoover** [comment]
This is a duplicate of #172, fixed in #176 this morning. Try again with the latest master, or wait for a release later this week!

**Comment by beckermr** [comment]
Ohhh cool! Thanks!
