### ISSUE TITLE
Civis joblib backend can ignore n_jobs restriction

### ISSUE THREAD

**Issue by stephen-hoover** [civisanalytics/civis-python#206]
In v1.7, the Civis joblib backend gained the ability to set itself as the backend inside child jobs. This means that child jobs which use joblib could also use the Civis joblib backend to paralellize themselves in different container scripts. These child jobs would be unaware of any jobs limit which the user set on the original joblib call, and wouldn't have a way to coordinate between themselves in any case. This could lead to users consuming drastically more resources than they expected.

A further two points: 
- The addition of this feature in v1.7 defaulted to setting the remote backend to "civis", which altered the previous behavior of the Civis joblib backend (it didn't launch jobs from inside jobs before). 
- This behavior differs from the way that joblib treats parallel computation with multiprocessing. Attempting to multiprocess from inside a multiprocessed job results in ~~an error~~ joblib defaulting to running serially.

I think that in principle, the Civis joblib backend is doing what it should -- resources in the cloud aren't limited in the same way that resources on a local machine are. But the inability to control resource use isn't good, and the hard-to-notice change in default behavior also isn't good. We should switch to "threading" as the default `remote_backend` so that users need to request the new, more aggressive behavior (and manage the total number of jobs through `n_jobs` parameters inside whatever they're calling). It would be much more difficult to try to make the `n_jobs` parameter on the Civis joblib backend actually restrict the total number of jobs when using `remote_backend = "civis"`, so for now I think we should settle for documenting.

**Comment by stephen-hoover** [comment]
@beckermr , does this cover the motivation for #205 ?
CC @elsander for visibility.

**Comment by beckermr** [comment]
Yep this looks good!

**Comment by beckermr** [comment]
Note that I switched this to the 'sequential' backend since this forces serial operation even if there is a nested context manager which makes the code exactly backwards compatible.
