### ISSUE TITLE
Surface the documentation for civis.find and civis.find_one

### ISSUE THREAD

**Issue by jacksonllee** [civisanalytics/civis-python#235]
The docstrings for `civis.find` and `civis.find_one` have been recently added at #224, but the two functions aren't explicitly mentioned anywhere in the current Sphinx documentation. Currently there isn't a page dedicated to utility functions of this sort. Given that their major use case is to filter `civis.response.Response` objects, how about adding a section like "Utility Functions" or something in [`responses.rst`](https://github.com/civisanalytics/civis-python/blob/master/docs/source/responses.rst)?

@stephen-hoover @keithing

**Comment by stephen-hoover** [comment]
I agree that surfacing that documentation would be nice. It doesn't look like `responses.rst` makes it into the built documentation, though. It's also pretty empty. Maybe we could add a note about `find` and `find_one` in `user_guide.rst` under "Working Directly with the Client"?

**Comment by jacksonllee** [comment]
> It doesn't look like responses.rst makes it into the built documentation, though.

I thought [this page](http://civis-python.readthedocs.io/en/v1.8.1/responses.html) was the result of `responses.rst`?

**Comment by stephen-hoover** [comment]
You're right! My apologies. I do still think that these functions could make more sense in the `user_guide.rst` file, but they might also work in `responses.rst` if that section gets some explanatory text..

**Comment by jacksonllee** [comment]
Looking more closely, the `user_guide.rst` seems to be the helper-y kind for what I was getting at above, and it's more front and center than the more embedded/hidden page of `responses.rst`. So adding a note about `find` and `find_one` in `user_guide.rst` sounds like a good idea to me. Though in terms of style, this page is written mostly in prose, and so adding also in this page the Sphinx-ified docstrings (which I'd like to see in the docs somewhere) of `find` and `find_one` would look less than ideal. Maybe we should have a brief note (in prose) in `user_guide.rst`, with the hyperlinks pointing to docstrings shown in `responses.rst`? I'll make a PR and see how things go.
