### ISSUE TITLE
Add `query_to_civis_file` function

### ISSUE THREAD

**Issue by keithing** [civisanalytics/civis-python#237]
@stephen-hoover I wonder if you've mentioned this before?  It seems like it might be useful to return the file_id from a SQL query without requiring the user to download the result (as in `read_civis_sql`).

cc @jkulzick

**Comment by jkulzick** [comment]
I can see situations where just a file_id would be useful.

**Comment by stephen-hoover** [comment]
I think that the easiest way to do this would be to make some sort of "run_sql" helper function available. That could mean promoting `civis.io._tables._sql_script` to a public function and changing its output to be a `CivisFuture`.

FWIW, this can be as few as two lines:
```python
sql_script = client.scripts.post_sql(...)
sql_fut = civis.utils.run_job(sql_script.id)
```
and the file ID is in `sql_fut.result().output[0].file_id`.

**Comment by stephen-hoover** [comment]
This was added in #238 .
