### ISSUE TITLE
Encoding Error

### ISSUE THREAD

**Issue by alexm1309** [civisanalytics/civis-python#268]
When using read_civis() on a table that contains accented characters, the function will fail with a UnicodeDecodeError even if you specify the encoding argument.

So something like

civis.io.read_civis(table='schema.table_with_accented_characters', database='Database Name', use_pandas=False, encoding='latin-1')

Will fail with:

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc3 in position 106622: unexpected end of data

It sounds like we do some utf-8 encoding before the client reads the kwargs of read_civis() and that's where the error is surfacing.

**Comment by stephen-hoover** [comment]
I haven't been able to reproduce this error. Please reopen with a reproducible example if it happens again.
