### ISSUE TITLE
Possible to update to use newest version of pyyaml dependency?

### ISSUE THREAD

**Issue by mcoirad-gmmb** [civisanalytics/civis-python#292]
I think the latest pyyaml release is 5.1 but the requirements.txt lists only 3.99.
This causes incompatibility with the newest version of the 'googleads' module for example which depends on 5.1.
Possible to update?

**Comment by keithing** [comment]
I opened #293 to update this.  It may take some time for a release, but after this merged this will fix the issue if you pull from master.

**Comment by mcoirad-gmmb** [comment]
Thanks! I will pull from here once it merges.
