### ISSUE TITLE
CLI: GET /aliases/{alias} endpoint is inaccessible

### ISSUE THREAD

**Issue by jacksonllee** [civisanalytics/civis-python#298]
The CLI emitted a confusing `UserWarning` of `UserWarning: conflicting command name: get` when I used the terminal command of `civis files download <file-id> <filename>`. This is the line that triggered the said `UserWarning`:

https://github.com/civisanalytics/civis-python/blob/v1.10.0/civis/cli/__main__.py#L287

My CLI file download operation succeeded and got me the file I needed, with no errors or other warnings. We should look into what triggers the `UserWarning` and suppress/remove/fix it as appropriate, though this ticket is probably low-priority.

**Comment by stephen-hoover** [comment]
I poked into this. The warning indicates which line it's coming from. This is the CLI-autogeneration code. The Platform "alias" endpoint has one command with a form that the CLI-autogeneration code doesn't recognize. In particular, it can't distinguish between GET /aliases/{alias} and GET /aliases/{object_type}/{alias}.

The {object_type} entry comes second, so it clobbers the GET /aliases/{alias} in the CLI. I'm reclassifying this as "Bug" -- until it's fixed, users won't be able to use GET /aliases/{alias} through the CLI.
