### ISSUE TITLE
Pyyaml requirements differ on github from package on pypi.org

### ISSUE THREAD

**Issue by mcoirad-gmmb** [civisanalytics/civis-python#313]
The latest 1.10.0 version of the civis python package on github lists its pyyaml requirement as "pyyaml>=3.0,<=5.99" [(link)](https://github.com/civisanalytics/civis-python/blob/master/requirements.txt) but downloading the source of 1.10.0 on pypi.org [(link)](https://pypi.org/project/civis/1.10.0/#files) the requirement is "pyyaml>=3.0,<=3.99"

When using the default source in pip to install this can cause problems, as some other packages require pyyaml > 3.99

**Comment by mcoirad-gmmb** [comment]
Sorry, my bad, the release of 1.10 was back in April -- requirements only updated recently.

**Comment by stephen-hoover** [comment]
Yes, we updated the requirements in https://github.com/civisanalytics/civis-python/pull/293 . It will be included in the next release.
