### ISSUE TITLE
parameterize index in civis.io.dataframe_to_civis

### ISSUE THREAD

**Issue by nickahamed** [civisanalytics/civis-python#61]
@keithing I use `civis.io.dataframe_to_civis` to write to redshift, and had meaningfull indexes but these weren't written and it doesn't appear there's the ability at all to write them. We may want to make this a parameter (which would get passed to to_csv).

**Comment by stephen-hoover** [comment]
@nickahamed , if you call `dataframe_to_civis` with `df.reset_index()` instead of `df` (assuming your `DataFrame` is named `df`), that will include your index as the first column of the table. That seems simpler than adding a parameter to the `dataframe_to_civis` function.

**Comment by nickahamed** [comment]
yeah, I got there eventually. Just not as intuitive for the intro python user. I don't know if we can add that recommendation into the docs somehow so folks aren't left puzzled.
